#
# Hardware settings for my H310M S2H Desktop
#
# flake.nix
#  └─ ./hosts
#      └─ ./h310m
#          ├─ default.nix
#          └─ hardware-configuration.nix *
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#

{ config, lib, modulesPath, vars, host, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  #boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/037a2ca9-3c4d-4f2e-97aa-f83b511d3410";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/037a2ca9-3c4d-4f2e-97aa-f83b511d3410";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/037a2ca9-3c4d-4f2e-97aa-f83b511d3410";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EF90-63D5";
      fsType = "vfat";
    };

  swapDevices = [ ];

#  fileSystems."/storage" =
#    {
#      device = "//192.168.0.3/storage";
#      fsType = "cifs";
#      options =
#        let
#          automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
#        in
#        [ "${automount_opts},mfsymlinks,uid=1000,gid=100,credentials=/home/${vars.user}/smb" ];
#    };

#  fileSystems."/media" =
#    {
#      device = "//192.168.0.3/media";
#      fsType = "cifs";
#      options =
#        let
#          automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
#        in
#        [ "${automount_opts},mfsymlinks,uid=1000,gid=100,credentials=/home/${vars.user}/smb" ];
#    };

#  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking = with host; {
    useDHCP = true;
    hostName = hostName;
    hostId = "ca2486b7";
    enableIPv6 = false;
    nameservers = [ "192.168.0.4" "1.1.1.1" ];
  };
}
